version: 2.1
orbs:
  java: circleci/openjdk@1.0.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
      - image: selenium/standalone-chrome:latest
        name: chrome
    steps:
      - checkout
      - java/with_cache:
          steps:
            - run: mvn clean install
            - run: mvn test
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/site
          destination: site
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
