version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
      - image: selenium/standalone-chrome:latest
        name: chrome
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Install Maven Wrapper
          command: |
            sudo apt-get update
            sudo apt-get install -y maven
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn clean install
      - run: mvn test
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/site
          destination: site

workflows:
  version: 2
  build-deploy:
    jobs:
      - build