version: 2.1

jobs:
  test:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/project
    steps:
      - checkout
      - run: sudo apt-get update
      - run: apt-get update
      - run: apt-get install -y maven
      - run: mvn test
      - store_test_results:
          path: target/surefire-reports

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test