version: 2.1

jobs:
  test:
    docker:
      - image: circleci/openjdk:11-jdk
        environment:
          JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64/
    working_directory: ~/project
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -y maven
      - run:
          name: Run tests and copy results
          command: |
            echo "project.build.directory=${project.build.directory}"
            mvn test -Dtest=Runner -Dcucumber.features="$(pwd)/src/test/feature/"
            sudo mkdir -p $CIRCLE_TEST_REPORTS/
            sudo cp -r "$CIRCLE_WORKING_DIRECTORY/target/cucumber-html-report/"*.html $CIRCLE_ARTIFACTS/
          path: /home/circleci/project
      - store_artifacts:
          path: $CIRCLE_WORKING_DIRECTORY/target/cucumber-html-report/
          destination: cucumber-html-report
      - store_artifacts:
          path: $CIRCLE_WORKING_DIRECTORY/target/surefire-reports/

workflows:
  version: 2
  test:
    jobs:
      - test