version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout

      - run:
          name: build
          command: |
            mvn clean install

      - run:
          name: Run Maven tests with -x flag
          command: mvn test -B -x

  test:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout

      - run:
          name: test
          command: |
            mvn clean test

      - store_test_results:
          path: target/surefire-reports

      - run:
          name: create report
          command: |
            mvn verify

      - run: mvn clean test -Dtest=TestRunner -Dcucumber.options="--plugin io.cucumber.junit.CucumberOptions,--plugin json:target/cucumber-report/cucumber.json" -X

      - store_artifacts:
          path: target/cucumber-html-reports/
          destination: cucumber-reports/

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build