version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:2021.04
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y maven openjdk-11-jdk
            curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
            sudo apt-get -y update
            sudo apt-get -y install google-chrome-stable
      - run:
          name: Setup WebDriver Manager
          command: |
            sudo apt-get install -y wget
            wget https://repo1.maven.org/maven2/io/github/bonigarcia/webdrivermanager/5.0.3/webdrivermanager-5.0.3-standalone.jar
            java -jar webdrivermanager-5.0.3-standalone.jar chromedriver --force-download --export
      - run:
          name: Run tests and copy results
          command: |
            export PROJECT_BUILD_DIRECTORY=$project.build.directory
            echo "project.build.directory=${PROJECT_BUILD_DIRECTORY}"
            mvn test -Dtest=Runner -Dcucumber.features="$(pwd)/src/test/feature/" -Dwebdriver.chrome.driver=$(pwd)/chromedriver
            sudo mkdir -p $CIRCLE_TEST_REPORTS/
            sudo cp -r "$CIRCLE_WORKING_DIRECTORY/target/cucumber-html-report/"*.html $CIRCLE_ARTIFACTS/
            sudo cp -r "$CIRCLE_WORKING_DIRECTORY/target/surefire-reports/" $CIRCLE_TEST_REPORTS/
      - store_artifacts:
          path: $CIRCLE_WORKING_DIRECTORY/target/cucumber-html-report/
          destination: cucumber-html-report
      - store_artifacts:
          path: $CIRCLE_WORKING_DIRECTORY/target/surefire-reports/

workflows:
  test:
    jobs:
      - test