version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout

      - run:
          name: Build and test
          command: |
            mvn clean test

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/cucumber-html-reports/
          destination: cucumber-reports/

workflows:
  build_and_test:
    jobs:
      - build