version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y maven

      - run:
          name: Build project
          command: |
            mvn clean install

  test:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y maven

      - run:
          name: Run unit tests
          command: |
            mvn clean test

      - run:
          name: Generate test report
          command: |
            mvn verify

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/cucumber-html-reports/
          destination: cucumber-reports/

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build