version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y maven
      - run: mvn test -Dtest=RunCucumberTest -Dcucumber.options="--plugin junit:$CIRCLE_WORKING_DIRECTORY/target/cucumber-reports/Cucumber.xml"
      - store_test_results:
          path: $CIRCLE_WORKING_DIRECTORY/target/cucumber-html-reports.html

workflows:
  version: 2
  test:
    jobs:
      - build