version: 2.1

jobs:
  test:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/project
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -y maven
      - run: mvn test
      - run:
            name: Run tests
            command: |
             mvn test
             mkdir -p $CIRCLE_TEST_REPORTS/junit/
             cp target/surefire-reports/*.xml $CIRCLE_TEST_REPORTS/junit/
             path: /home/circleci/project

      - store_test_results:
          path: /home/circleci/project/target/surefire-reports
      - store_artifacts:
          path: /home/circleci/project/target/cucumber-html-report.html

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test