version: 2.1

jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Install Maven
          command: |
            sudo apt-get update
            sudo apt-get install -y maven

      - run:
          name: Run Tests
          command: mvn test