version: 2.1

jobs:
  test:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/project
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -y maven
      - run:
          name: Run tests and copy results
          command: |
            echo "project.build.directory=$${project.build.directory}"
            mvn test
            sudo mkdir -p $CIRCLE_TEST_REPORTS/junit/
            pwd
            ls -l target/surefire-reports/
            sudo cp -r "${project.build.directory}/cucumber-jvm-report/"*.xml $CIRCLE_TEST_REPORTS/junit/
          path: /home/circleci/project
      - store_test_results:
          path: /home/circleci/project/target/surefire-reports
      - store_artifacts:
          path: /home/circleci/project/target/cucumber-html-report.html

workflows:
  version: 2
  test:
    jobs:
      - test