version: 2.1

jobs:
  test:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/project
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install -y maven
      - run: mvn test

workflows:
  version: 2
  test :
    jobs:
      - test