version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout

      - run:
          name: install maven
          command: |
            sudo apt-get update
            sudo apt-get install -y maven

      - run:
          name: build
          command: |
            mvn clean install

  test:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout

      - run:
          name: install maven
          command: |
            sudo apt-get update
            sudo apt-get install -y maven

      - run:
          name: test
          command: |
            mvn clean test

      - store_test_results:
          path: target/surefire-reports

      - run:
          name: create report
          command: |
            mvn verify

      - store_artifacts:
          path: target/cucumber-html-report.html/
          destination: cucumber-reports/

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build