version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.6-jdk-11
    steps:
      - checkout
      - run: mvn clean install

  test:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Install ChromeDriver
          command: |
            LATEST=`curl -sSL https://chromedriver.storage.googleapis.com/LATEST_RELEASE`
            curl -sSL https://chromedriver.storage.googleapis.com/$LATEST/chromedriver_linux64.zip -o chromedriver.zip
            unzip chromedriver.zip -d /home/circleci/bin
            rm chromedriver.zip
      - run:
          name: Run tests
          command: mvn test
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/site/serenity

workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build