version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout

      - run:
          name: test
          command: |
            mvn clean test -Dsurefire.useFile=false -Dsurefire.reportName=TEST-result.xml

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/cucumber-html-reports/
          destination: cucumber-reports/
          when: always
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: mvn test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build